I am updating the this code for demo
Hello i am upadting this file in master branch
Hello i am updating in deve branch
Hello i am updating this file ...
Every one stay alert
This file contains some string related functions .....
